### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by jxom** [wevm/viem#29]
# Tracking

A list of stuff that needs to be done before public release.

## Clients

- [x] `createClient`: Base Client
- [x] `createPublicClient`: Public Client
- [x] `createWalletClient`: Wallet Client
- [x] `createTestClient`: Test Client

### Transports
- [x] `http`: HTTP
- [x] `webSocket`: WebSocket
- [x] `custom`: Custom EIP-1193
- [x] `fallback`: Fallback
  - [ ] Quorum & Weights
  - [ ] Priorities
  - [ ] Roundrobin (Random Pick)
- [ ] `ipc`: IPC
- [x] **Misc: `timeout` config option**
- [x] Misc: `retryCount` config option

### RPC
- [x] Retry Support
- [x] Timeout Support
- [x] **Transport Headers (+ Auth)**
- [x] Transport Methods
  - [x] HTTP
  - [x] WebSocket
- [ ] [Batching](https://www.jsonrpc.org/specification#batch)

## Chains

- [x] Chain Formatters (custom JSON-RPC request/response types)

### Account

- [x] `getBalance`
- [x] `getTransactionCount`

### Block

- [x] `getBlock`
- [x] `getBlockNumber`
- [x] `getBlockTransactionCount`
- [x] `watchBlockNumber`
  - [ ] WebSocket: Support with `eth_subscribe` + `watchHeads`
- [x] `watchBlocks`
  - [ ] WebSocket: Support with `eth_subscribe` + `watchHeads`

### Chain

- [x] `getChainId`

### ENS

- [x] `getEnsAddress` @tmm 
- [x] `getEnsName` @tmm 
- [ ] **`getEnsResolver`** @tmm

### Fee

- [x] `estimateGas`
- [x] `getFeeHistory`
- [x] `getGasPrice`
- [ ] `watchGasPrice`

### Filters & Logs

- [x] `createBlockFilter`
- [x] `createEventFilter`
  - [x] Support `args`
- [x] `createPendingTransactionFilter`
- [x] `getFilterChanges`
- [x] `getFilterLogs`
- [x] `getLogs` @0xOlias 
- [x] `watchEvents`
  - [ ] Support `fromBlock` 
  - [x] Support nodes that do not implement `eth_newFilter`
  - [ ] WebSocket: Support with `eth_subscribe` + `logs`
- [x] `uninstallFilter`

### Transaction

- [x] `call`
- [x] `getTransaction`
- [x] `getTransactionConfirmations`
- [x] `getTransactionReceipt`
- [ ] `sendRawTransaction`
- [x] `waitForTransactionReceipt`
- [x] `watchPendingTransactions`
  - [ ] Resolve transactions via a `full` arg w/ `getTransaction`
  - [ ] WebSocket: Support with `eth_subscribe` + `newPendingTransactions`

### Account

- [x] `getAccounts`
- [x] `requestAccounts`

### Assets

- [x] `watchAsset`

### Chain

- [x] `addChain`
- [x] `switchChain`

### Data

- [x] `signMessage`
- [ ] **`signTypedData`** @jxom 

### Permissions

- [x] `getPermissions`
- [x] `requestPermissions`

### Transaction

- [x] `sendTransaction`
- [ ] `signTransaction`

### Account

- [x] `impersonateAccount`
- [x] `setBalance`
- [x] `setCode`
- [x] `setNonce`
- [x] `setStorageAt`
- [x] `stopImpersonatingAccount`

### Block

- [x] `getAutomine`
- [x] `increaseTime`
- [x] `mine`
- [x] `removeBlockTimestampInterval`
- [x] `setAutomine`
- [x] `setIntervalMining`
- [x] `setBlockTimestampInterval`
- [x] `setBlockGasLimit`
- [x] `setNextBlockBaseFeePerGas`
- [x] `setNextBlockTimestamp`

### Node

- [x] `setCoinbase`
- [x] `setMinGasPrice`

### Settings

- [x] `reset`
- [x] `setLoggingEnabled`
- [x] `setRpcUrl`

### State

- [x] `revert`
- [x] `snapshot`

### Transaction

- [x] `dropTransaction`
- [x] `getTxpoolContent`
- [x] `getTxpoolStatus`
- [x] `inspectTxpool`
- [x] `sendUnsignedTransaction`

## Contract

- [ ] CCIP Read
- [ ] `fallback()` & `receive()` function support

### Actions

- [x] `deployContract`
- [x] `createContractEventFilter`
- [x] `estimateContractGas`
- [x] `getBytecode`
- [x] `getStorageAt`
- [x] `multicall`
- [x] `readContract`
- [x] `simulateContract`
- [x] `writeContract`
- [x] `watchContractEvents` 
  - [x] decode `topics`

### Encoding

- [x] `decodeDeployData`
- [x] `decodeErrorResult`
- [x] `decodeEventTopics`
- [x] `decodeFunctionData`
- [x] `decodeFunctionResult`
- [x] `encodeDeployData`
- [x] `encodeErrorResult`
- [x] `encodeEventTopics`
- [x] `encodeFunctionData`
- [x] `encodeFunctionResult`

## ABI

- [x] `decodeAbiParameters`
- [x] `encodeAbiParameters`
- [ ] `getAbiItem`
- [ ] `parseAbi` & `ParseAbi` (human readable -> json) @tmm 
- [ ] `parseAbiItem` & `ParseAbiItem` @tmm
  - [ ] parseAbiConstructor
  - [ ] parseAbiEvent
  - [ ] parseAbiError
  - [ ] parseAbiFallback
  - [ ] parseAbiFunction
- [ ] `parseAbiParameter` & `ParseAbiParameter` @tmm
- [ ] `parseAbiParameters` & `ParseAbiParameters` @tmm

### Addresses

- [x] `getAddress`
- [x] `getContractAddress`
- [x] `isAddress`
- [x] `isAddressEqual`

### Data

- [x] `concat`
- [x] `isBytes`
- [x] `isHex`
- [x] `pad`
- [x] `slice`
- [x] `size`
- [x] `trim`

### Encoding

- [ ] `fromBase58`
- [ ] `fromBase64`
- [x] `fromBytes`
- [x] `fromHex`
- [x] `fromRlp`
- [ ] `toBase58`
- [ ] `toBase64`
- [x] `toBytes`
- [x] `toHex`
- [ ] `toPacked`
- [x] `toRlp`

### ENS
 
- [x] `labelhash` @tmm
- [x] `namehash` @tmm
- [x] `normalize` @tmm

### Hash

- [x] `getEventSignature`
- [x] `getFunctionSignature`
- [x] `keccak256`

### Units

- [x] `formatEther`
- [x] `formatGwei`
- [x] `formatUnit`
- [x] `parseEther`
- [x] `parseGwei`
- [x] `parseUnit`

### Verification

- [ ] `verifyMessage`
- [ ] `verifyTypedData`

### Introdution

- [ ] **Why viem**
- [x] Getting Started
- [ ] **Library Comparison**

### Clients & Transports

- [x] Introduction
- [ ] **Chains**
- [ ] **Callout/example of Actions in Public, Wallet, Test Clients**

### Public Actions

- [ ] **Introduction**
- [ ] **List RPC method(s) used for actions (within each action page)**

### Wallet Actions

- [ ] **Introduction**
- [ ] **List RPC method(s) used for actions (within each action page)**

### Test Actions

- [ ] **Introduction**
- [ ] **List RPC method(s) used for actions (within each action page)**

### Contracts

- [ ] **Introduction**
- [ ] Replace `encodeAbi`/`decodeAbi` "Usage" snippets with a "real life" one
- [ ] Add more complex & "real life" encoding examples (`encodeAbi`, `encodeFunctionData` etc)
- [ ] Include notes in encoding utils of what Contract Actions are using them
  - e.g. `readContract` uses `encodeFunctionData` and `decodeFunctionResult` . 

### Examples

- Blocks
  - [x] Fetching Blocks
  - [ ] Watching Blocks
- Contracts
  - [ ] Deploying
  - [x] Reading
  - [ ] Writing
  - [ ] Multicall
  - [ ] Call
  - [ ] Events
  - [ ] Simulating Method Calls
- Clients
  - [x] Public (w/ HTTP, WebSocket, Fallback)
  - [x] Wallet (w/ `window.ethereum`, WalletConnect v2, Coinbase SDK)
  - [ ] Test (w/ Anvil HTTP/WS, Hardhat HTTP/WS)
- ENS
  - [ ] Address from ENS Name
  - [ ] ENS Name from Address
  - [ ] Fetch ENS Resolver
- Filters & Logs
  - [ ] Blocks
  - [ ] Pending Transactions
  - [ ] Events
- Anvil/Hardhat
  - [ ] Impersonating Accounts
  - [ ] Setting Balances
  - [ ] Mining (mine, automining, interval mining, etc)
  - [ ] Resetting Forks
  - [ ] State (snapshot/revert)
  - [ ] Tx pools
- Transactions
  - [ ] Fetching Transactions & Receipts
  - [ ] Transaction Types (EIP-1559, Legacy, etc)
  - [ ] Simulating Transactions
  - [x] Sending Transactions (& Waiting for Receipt)

### Glossary

- [ ] Terms
- [ ] Types

### Misc

- [ ] **Ethers -> viem migration guide**
- [ ] **OG/meta tags**
- [ ] **Node <18 Polyfills (`fetch`)**
- [x] Entrypoints
  - `viem/public`
  - `viem/wallet`
  - `viem/test`
  - `viem/utils`
